authorization_server/models.py
import uuid

from datetime import datetime
from flask_login import UserMixin
from authorization_server.app import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return db.session.query(User).get(user_id)


class User(db.Model, UserMixin):

    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(length=20))
    lastname = db.Column(db.String(length=40))
    email = db.Column(db.String(length=50), nullable=False, unique=True)
    password = db.Column(db.String(length=128))


class Application(db.Model):

    __tablename__ = 'application'
    id = db.Column(db.String(length=40), primary_key=True, nullable=False)
    client_secret = db.Column(db.String(length=128))
    reg_token = db.Column(db.String(length=40), unique=True)
    email = db.Column(db.String(length=50), unique=True, nullable=False)
    name = db.Column(db.String(length=50), nullable=False)
    description = db.Column(db.String(length=255), nullable=False)
    web_url = db.Column(db.String(length=255), unique=True, nullable=False)
    redirect_uri = db.Column(db.String(length=255), unique=True, nullable=False)
    active = db.Column(db.Boolean, default=True)
    is_allowed = db.Column(db.Boolean, default=False)
    created = db.Column(db.DateTime, default=datetime.now)
    updated = db.Column(db.DateTime)
    authorisation_code = db.relationship("AuthorisationCode", back_populates='application')

    @classmethod
    def generate_id(cls):
        return str(uuid.uuid4()).replace('-', '')


class AuthorisationCode(db.Model):

    __tablename__ = 'authorisation_code'
    id = db.Column(db.Integer, primary_key=True)
    created = db.Column(db.DateTime, default=datetime.now)
    updated = db.Column(db.DateTime)
    used = db.Column(db.Boolean, default=False)
    application_id = db.Column(db.String(length=40), db.ForeignKey('application.id'))
    application = db.relationship('Application', back_populates='authorisation_code')

authorization_server/frontend/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError
from authorization_server.app import db
from authorization_server import models

INVALID_EMAIL_ERROR = 'Please enter a valid email address'
EMAIL_EXIST_ERROR = 'The email provided already exists. Please use another one'
INVALID_PASSWORD_ERROR = 'Your password must be between 8 and 15 characters long'
DIFFERENT_PASSWORD_ERROR = 'Please enter the same password again'


class RegistrationForm(FlaskForm):
    firstname = StringField('First Name', validators=[DataRequired()])
    lastname = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email Address', validators=[DataRequired(),
                                                     Email(message=INVALID_EMAIL_ERROR)])
    password = PasswordField('Password',
                             validators=[Length(min=8, max=15,
                                                message=INVALID_PASSWORD_ERROR)])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(),
                                                 EqualTo('password', message=DIFFERENT_PASSWORD_ERROR)])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        data = db.session.query(models.User).filter(models.User.email == email.data).first()
        if data:
            raise ValidationError(EMAIL_EXIST_ERROR)


class LoginForm(FlaskForm):
    email = StringField('Email Address', validators=[DataRequired(),
                                                     Email(message=INVALID_EMAIL_ERROR)])
    password = PasswordField('Password',
                             validators=[Length(min=8, max=15,
                                                message=INVALID_PASSWORD_ERROR)])


class SimpleLoginForm(LoginForm):
    submit = SubmitField('Sign In')


class GrandTypeLoginForm(LoginForm):
    cancel = SubmitField('Cancel')
    allow = SubmitField('Allow')

authorization_server/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_beaker_session import session as beaker_session
from authorization_server import config

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
session = beaker_session.Session()
login_manager = LoginManager()
login_manager.login_view = "frontend.login"
login_manager.login_message = "Please log in to see restricted access web pages"
login_manager.login_message_category = "info"


def create_app(config_class=config.Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    session.init_app(app)
    # require to import models here so that migrate knows what to generate
    from authorization_server import models
    migrate.init_app(app, db)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    from authorization_server.frontend.views import frontend
    from authorization_server.apis.handler import api_v1
    from authorization_server.auth.views import auth
    app.register_blueprint(frontend, url_prefix='/')
    app.register_blueprint(api_v1, url_prefix='/api')
    app.register_blueprint(auth, url_prefix='/auth')

    return app

authorization_server/frontend/views.py
from flask import Blueprint, render_template, request, redirect,  url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from authorization_server.frontend.forms import RegistrationForm, SimpleLoginForm, GrandTypeLoginForm
from authorization_server import models, oauth_code
from authorization_server.app import db, bcrypt

frontend = Blueprint('frontend', __name__, static_folder='../static/frontend')
LOGIN_ERROR_MESSAGE = 'Login Unsuccessful. Please check email and password'


@frontend.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        enc_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = models.User(**{key: value for key, value in form.data.items()
                              if key not in ('confirm_password', 'submit', 'csrf_token')})
        user.password = enc_password
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('frontend.login'))
    return render_template('frontend/register.html', form=form)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    client_app = None
    is_grand_type = request.args.get('grand_type')
    if is_grand_type == 'code':
        auth_code = oauth_code.AuthorisationCode(**request.args)
        client_app = {'name': 'Application Name', 'web_url': 'https://www.bbc.co.uk'}
        form = GrandTypeLoginForm()
    else:
        form = SimpleLoginForm()

    if current_user.is_authenticated:
        return redirect(url_for('frontend.profile'))
    if form.validate_on_submit():
        user = db.session.query(models.User).filter(models.User.email == form.email.data).first()
        if not user or not bcrypt.check_password_hash(user.password, form.password.data):
            flash(LOGIN_ERROR_MESSAGE, category='danger')
        else:
            login_user(user)
            return redirect(url_for('frontend.profile'))
    return render_template('frontend/login.html', form=form, client_app=client_app, test=type(is_grand_type))


@frontend.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('frontend.login'))


@frontend.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    return render_template('frontend/profile.html')

authorization_server/templates/frontend/include/dialog.html
<div id="dialog-confirm" title="{{ d_title|default("Action Required!", true) }}">
    <p id="d_content">{{ d_content|default("Are you sure you want to carry on with this operation?",true) }}</p>
</div>

authorization_server/templates/frontend/include/login_button.html
{{ form.submit(class="btn btn-lg btn-primary btn-block", id='sing_in') }}

authorization_server/templates/frontend/include/login_heading.html
<h2>Sign In</h2>
<hr>

authorization_server/templates/frontend/include/message.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

authorization_server/templates/frontend/login.html
{% extends 'layout.html' %}
{% block header %}
    {# Include auth blueprint's stylesheet when Grand Type Login  #}
    {% if client_app %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('auth.static', filename='css/main.css') }}">
    {% else %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('frontend.static', filename='css/main.css') }}">
    {% endif %}
    <script type="text/javascript" src="{{ url_for('frontend.static', filename='js/validators.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('frontend.static', filename='js/include/dialog.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('frontend.static', filename='js/login.js') }}"></script>
{% endblock header %}
{% block content %}
    <div class="signup-form">
        <form id="signin-form" method="POST" action="">
            {{ form.hidden_tag() }}
            {# Show Client App details section when Grand Type Login #}
            {% if client_app %}
                {% include 'include/client_app_details.html' %}
            {% else %}
                {% include 'frontend/include/login_heading.html' %}
            {% endif %}
            <div class="form-group">
                {% include 'frontend/include/message.html' %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="sr-only", for="email") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid", id="email", placeholder="Email Address") }}
                    {% for error in form.email.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form-control", id="email", placeholder="Email Address") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="sr-only", for="password") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid", id="password", placeholder="Password") }}
                    {% for error in form.password.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form-control", id="password", placeholder="Password") }}
                {% endif %}
            </div>
            {# Show the Scopes and Resource Owner's warning message sections when Grand Type Login #}
            {% if client_app %}
                <div class="form-group buttons-row">
                    {% include 'include/client_request_scope.html' %}
                </div>
                <div class="form-group buttons-row">
                    {% include 'include/resource_owner_warning.html' %}
                </div>
            {% endif %}
            {# Show Allow-Cancel buttons pair section when Grand Type Login #}
            <div class="form-group  buttons-row">
                {% if client_app %}
                    {% include 'include/grand_type_allow_cancel_buttons.html' %}
                {% else %}
                    {% include 'frontend/include/login_button.html' %}
                {% endif %}
            </div>
            <div class="clearfix">
                <a href="#" id='forgot_password' class="pull-right">Forgot Password?</a>
            </div>
        </form>
        <div class="text-center"><a href="{{ url_for('frontend.register') }}">Create Account?</a></div>
    </div>
    {% include 'frontend/include/dialog.html' %}
{% endblock content %}

authorization_server/templates/frontend/profile.html
{% block header %}
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet"
          id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
{% endblock header %}
{% block content %}
    <div class="container-fluid well span6">
        <h2>Account Details</h2>
        <div class="row-fluid">
            <div class="span2">
                <img src="{{ url_for('frontend.static', filename='images/girl.png') }}"
                     class="img-circle">
            </div>

            <div class="span8">
                <h3>{{ current_user.firstname|capitalize }} {{ current_user.lastname|capitalize }}</h3>
                <h6>Email: {{ current_user.email }}</h6>
            </div>

            <div class="span2">
                <div class="btn-group">
                    <a class="btn dropdown-toggle btn-info" data-toggle="dropdown"
                       href="{{ url_for('frontend.logout') }}">Logout</a>
                </div>
            </div>
        </div>
        <div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a
                href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
                href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC
            3.0 BY</a></div>
    </div>
{% endblock content %}

authorization_server/templates/frontend/register.html
{% extends 'layout.html' %}
{% block header %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('frontend.static', filename='css/main.css') }}">
    <script type="text/javascript" src="{{ url_for('frontend.static', filename='js/validators.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('frontend.static', filename='js/register.js') }}"></script>
{% endblock header %}
{% block content %}
    <div class="signup-form">
        <form id="signup-form" method="POST" action="">
            {{ form.hidden_tag() }}
            <h2>Sign Up</h2>
            <p>It's free and only takes a minute.</p>
            <hr>
            <div class="form-group">
                {{ form.firstname.label(class="sr-only", for="firstname") }}
                {% if form.firstname.errors %}
                    {{ form.firstname(class="form-control is-invalid", id="firstname", placeholder="First Name") }}
                    {% for error in form.firstname.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.firstname(class="form-control", id="firstname", placeholder="First Name", autofocus=true) }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.lastname.label(class="sr-only", for="lastname") }}
                {% if form.lastname.errors %}
                    {{ form.lastname(class="form-control is-invalid", id="lastname", placeholder="Last Name") }}
                    {% for error in form.lastname.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.lastname(class="form-control", id="lastname", placeholder="Last Name") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="sr-only", for="email") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid", id="email", placeholder="Email Address") }}
                    {% for error in form.email.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form-control", id="email", placeholder="Email Address") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="sr-only", for="password") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid", id="password", placeholder="Password") }}
                    {% for error in form.password.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form-control", id="password", placeholder="Password") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="sr-only", for="confirm_password") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid", id="confirm_password", placeholder="Confirm Password") }}
                    {% for error in form.confirm_password.errors %}
                        <span class="is-invalid">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.confirm_password(class="form-control", id="confirm_password", placeholder="Confirm Password") }}
                {% endif %}
            </div>
            <div class="form-group">
                 {{ form.submit(class="btn btn-lg btn-primary btn-block") }}
            </div>
            <p class="small text-center">By clicking the Sign Up button, you agree to our <br><a href="#">Terms &amp;
                Conditions</a>, and <a href="#">Privacy Policy</a>.</p>
        </form>
        <div class="text-center">Already have an account? <a href="{{ url_for('frontend.login') }}">Login here</a></div>
    </div>
{% endblock content %}

authorization_server/templates/include/client_app_details.html
<h2>{{ client_app.name }}</h2>
<hr>
<span class="web_url">{{ client_app.web_url }}</span>

authorization_server/templates/include/client_request_scope.html
<span class="text-warning">This application would like:</span>
<ul class="list-group text-info">
  <li class="list-group-item">To have access to your contact details</li>
  <li class="list-group-item">To create something</li>
  <li class="list-group-item">To edit something else</li>
</ul>

authorization_server/templates/include/grand_type_allow_cancel_buttons.html
{{ form.allow(class="btn btn-lg btn-primary btn-block float-left ml-1", id='allow') }}
{{ form.cancel(class="btn btn-lg btn-secondary btn-block float-right mr-1", id='cancel') }}

authorization_server/templates/include/resource_owner_warning.html
<span class="text-danger">If you do not understand <strong>neatly</strong> what this application need your permissions
    for as described above, we recommend to click 'Cancel' not to grant such permissions</span>

authorization_server/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    {% block header %}{% endblock header %}
    <title>{% block title %}  Frontend Authorisation Server {% endblock title %}</title>

</head>
<body class="text-center">
{% block content %}
{% endblock content %}
</body>
</html>